version: 2

sources:
  - name: office_weather
    schema: main

models:
  - name: extract_weather_data
    config:
      alias: latest_weather_readings
    tests:
      - unique:
          column_name: "time || '-' || office"

seeds:
  - name: office_locations
    columns:
      - name: lat
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -90
              max_value: 90

      - name: long
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: -180
              max_value: 180
