version: 2

sources:
  - name: library
    schema: main
    tables:
      - name: books_factual
      - name: books_fictional
      - name: loans
      - name: members

models:
  - name: stg_books
    columns:
      - name: book_id
        data_tests:
          - not_null
          - unique

  - name: stg_loans
    columns:
      - name: loan_id
        data_tests:
          - not_null
      - name: book_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_books')
              field: book_id
      - name: member_id
        data_tests:
          - not_null
          - relationships:
              to: ref('stg_members')
              field: member_id

  - name: stg_members
    columns:
      - name: membership_tier
        data_tests:
          - accepted_values:
              values: ["Bronze", "Silver", "Gold"]
      - name: member_id
        data_tests:
          - not_null

  - name: customers_with_late_fees
    tests:
      - dbt_utils.equal_rowcount:
          compare_model: ref('solution')
    columns:
      - name: fee_to_pay
        data_tests:
          - new_test

seeds:
  - name: solution
